### ISSUE TITLE
Fork paultyng/ghaction-import-gpg@v2.1.0 into Hashicorp's org

### ISSUE THREAD

**Issue by yannh** [hashicorp/terraform-provider-scaffolding#22] opened 2020-08-05 15:16 UTC
Hi @paultyng, 

Do you think you could fork the Github action paultyng/ghaction-import-gpg@v2.1.0 to Hashicorp's Github org? Since this deals with private GPG keys, it feels like it would be better to trust hashicorp than single employees. What do you think?

**Comment by paultyng** [comment] 2020-08-05 16:22
Yeah I don't disagree, I was hoping a cleaner / more official GPG action would show up to replace it. Let me investigate some. You could also fork it to your own repo if you felt more comfortable.

**Comment by crazy-max** [comment] 2020-08-18 12:20
Or maybe the original action [crazy-max/ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg)? I don't see any changes in your fork? If there is anything to improve it, let me know :)

**Comment by paultyng** [comment] 2020-12-14 18:20
@crazy-max sorry nothing personal there, in this case its mostly due to [limited authentication capabilities of GitHub actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions). You can pin to a SHA but its not necessarily guaranteed to be unchanged if you can reproduce the SHA, etc. and then you also won't get updates, so not ideal, and considering this is potentially running large organization private GPG keys through it, I think there is some sensitivity to using a third party.

**Comment by paultyng** [comment] 2020-12-14 18:23
We've already had this feedback about goreleaser in general, a company may need to run it through their internal third party approval process, and its just a source of friction to being able to publish, etc. (a source of friction we are comfortable with, but one nonetheless).

**Comment by ewilde-form3** [comment] 2021-04-23 07:42
@paultyng was there any update on moving this under the hashicorp organisation :pray:

**Comment by paultyng** [comment] 2021-04-23 20:23
@ewilde-form3 I am no longer at HashiCorp, I'm not sure where it stands.

**Comment by remyleone** [comment] 2021-04-30 16:50
I think it is done: https://github.com/hashicorp/ghaction-import-gpg

**Comment by bflad** [comment] 2021-09-27 21:05
This appears to have been previously done as the current workflow has `uses: hashicorp/ghaction-import-gpg@v2.1.0`: https://github.com/hashicorp/terraform-provider-scaffolding/blob/104365c705fd7c0a6ffc73d6841b6afabdb6b4a8/.github/workflows/release.yml#L32-L39

**Closed as completed by bflad** 2021-09-27 21:05 UTC
Labels: enhancement, question
